### Vector Spaces and Vectors:

*We discuss here vectors and vector spaces in general but we focus on the Euclidean Space*

A Vector Space , is defined by a set of vectors for example R3 (real numbers) is a vector space , 3 denominates the dimensions (x-axis,y-axis,z-axis) an element of R3 is called a vector and is represented as a linear combination of x,y,z .
Vectors can be added togther or multiplied by a scalar ( a real number) and respect the axioms of groups :

- That is given two vectors x,y we have the following :
    - There exists a zero-element called the null vector 0 such as x+0 = x
    - There exists an inverse element -x such as x + (-x) = 0
    - There exists a multiplicative identity such as 1x = x 
    - Commutativity (x+y = y+x) , Distributivity (m(y+z) = m*y + m*z) where m is a scalar , Associativity (x+(y+z) = (x+y+z) = (x+y)+z)


**P.S** : We can say that vectors are tuples of scalars .

- span of a set of vectors that is for example, span{x,y,z} is the set of all vectors that are linear combinations of {x,y,z} in other words all elements that can be written as ax+by+cz with (a,b,c) are real numbers constitute a span , the elements of a span are themselves vectors .

- the elements of a span if lineraly independant , meaning that if ax+by+cz = 0 => a=b=c =0 ,are called basis and represent the backbone of that vector space .

- the basis of R3 = (x,y,z) such as x = (1,0,0) , y =(0,1,0) ,z =(0,0,1) any vector v = ax+by+cz is equal to the null vector (0,0,0) implies a=b=c = 0 

- The Euclidean space basis is the set of vectors, Vi = {0,0,0,i,0,0...0} where the i-th value is 1 and the rest is zero x-axis is the vector x = (1,0,0) , y = (0,1,0) , z = (0,0,1) 

- vectors are represented in a column forms called column vectors 

**Linear Maps** : a Linear map is a function T : U -> V where U and V are vector spaces that satisfies T(x+y) = Tx+Ty and T(ax) = aTx . A Linear map is a function that operates on vectors **but** it's more precisely a transformation from one vector space to another . (*Mutli-variate functions operate on vectors but are not Linear maps*) .

The matrix-vector product is used to define the notion of a linear transformation, which is one of the key notions in the study of linear algebra. Multiplication by a matrix A ∈ Rm×n can be thought of as computing a linear transformation TA that takes n-vectors as inputs and produces m-vectors as outputs:

**Matrices** are groups of vectors (column-wise) they have a rectangular shape (square in case the number of rows is the sames as the number of columns), now every linear map can be written as a matrix 

Now we will take a look at operations on vectors and matrices .



In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3])

"R3 basis"
x = np.array([1,0,0])
y = np.array([0,1,0])
z = np.array([0,0,1])

"operations"
u = 5*x+3*y
v = 2*x + 0.3*y

print(u)
print(v)

[5 3 0]
[2.  0.3 0. ]


In [3]:
"matrices are multi dimensions let's create the linear map I that is the identity matrix of R3"
I = np.array([x,y,z])
print(I)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
"identity matrix is like a mirror it's the equivalent of 1 in numbers every matrix M multiplied by I is equal to M"
M = np.random.randn(3,3)
print(M)

[[ 0.18595127 -2.3745461   1.37523735]
 [-0.77113061  0.65455118  1.38924668]
 [ 1.07840709 -0.43058979  0.25444376]]


In [5]:
print(M.dot(I))

[[ 0.18595127 -2.3745461   1.37523735]
 [-0.77113061  0.65455118  1.38924668]
 [ 1.07840709 -0.43058979  0.25444376]]


In [6]:
"matrix or vector transpose is basically transformin the columns to rows from 0 to j"
"since vector are n*1 matrices transposing them is just writing them in row form instead of column "
print(M.T)


[[ 0.18595127 -0.77113061  1.07840709]
 [-2.3745461   0.65455118 -0.43058979]
 [ 1.37523735  1.38924668  0.25444376]]


In [7]:
"inverses : the inverse of a matrix A , is A^-1 such as A*A^-1 = I"
invM = np.linalg.inv(M)

print(invM.dot(M))

[[ 1.00000000e+00 -7.60759970e-17  4.83312022e-17]
 [ 2.42625840e-17  1.00000000e+00  2.88089247e-18]
 [-1.73401580e-17 -1.14362407e-17  1.00000000e+00]]


### Solving Linear Systems
sometimes we face a problem where we have to find a vector x such as Ax = b where A a matrix and b another vector
since there's no matrix division we can solve this by using matrix inverse since we have the following : 

- x = A-1 * b

*where A-1 is the inverse of A , we can do this in numpy fairly easily using the solve function *

Suppose the following problem

    x+3y+5z = 10
    2x+5y+z = 8
    2x+3y+8z = 3
    
Let's solve this one if you invert A by hand you'll find the x = (-9.3,5.18,0.75)


In [8]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
b = np.array([10,8,3])

"finding x"
x = np.linalg.solve(A,b)
print(x)

[-9.28  5.16  0.76]


### The Eigens Club

Eigenvectors of a matrix A (**SQUARE MATRICES ONLY**), is a set of vectors that scales the matrix for example if A has an eigenvector Vi then
A * Vi is a transformation to A a *scaling* the result of this operation is equal to Vi multiplied by it's eigenvalue this helps us to decompose a matrix A into a product of 3 matrices namely :

(1) A * v = lambda * v (where v is an eigenvector and lambda is the corresponding eigenvalue)

A = Q * V * Q^-1 

Where Q is a matrix whose vectors are the eigenvectors of A , V is a diagonal matrix where V(i,j) = E(i) if i=j 0 otherwise and Q^-1 is the eigenvectors matrix inversed .

By Hand to find the Eigenvalue one has to find the roots of the caracteristic polynomial of the matrix A,the eigenvectors can be found using (1) .

*P.S* : E(i) is the eigenvalue (i) of A 
*P.S 2* : Google's PageRank is an eigenvector calculation with the matrix of weblinks

In [9]:
A = np.array([[1,2,3],[5,4,6],[2,1,2]])

eigenvalues,eigenvectors = np.linalg.eig(A)

print("Eigenvalues : " ,eigenvalues)
print("Eigenvectors: " ,eigenvectors)

Eigenvalues :  [ 7.9579162  -1.25766471  0.2997485 ]
Eigenvectors:  [[-0.37294331 -0.8469192  -0.06850557]
 [-0.88647995  0.32638018 -0.82264159]
 [-0.2739828   0.41976641  0.5644181 ]]


**The Eigen decomposition is just one method to decompose matrices there are many more *SVD*,*LU*,*QR*,*Cholesky* ...** each has it's own usecase but they can all be computed using numpy .
